name: webwin

services:
  winnginx:
    image: nginx:latest
    container_name: winnginx
    ports:
     - "80:80"
    volumes:
      - "C:/Web/web/conf:/web/conf"
      - "C:/Web/web/x:/web/x"
      - "C:/Web/web/conf/config/nginxwin:/etc/nginx/conf.d"
      - "E:/Web/web/vid:/web/vid"
    restart: unless-stopped

  winlist:
    image: xhofe/alist:latest
    container_name: winlist
    ports:
     - "5245:5244"
    volumes:
      - "C:/Web/Database/alistdata:/opt/alist/data"
      - "E:/Web/list:/list"
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
