name: webwin

services:
  winnginx:
    image: nginx:latest
    container_name: winnginx
    ports:
     - "80:80"
    volumes:
      - "C:/Web/web/conf:/web/conf"
      - "C:/Web/web/x:/web/x"
      - "C:/Web/web/conf/config/nginxwin:/etc/nginx/conf.d"
      - "E:/Web/web/vid:/web/vid"
    restart: unless-stopped

  winlist:
    image: openlistteam/openlist:latest
    container_name: winlist
    user: '0:0'
    volumes:
      - "C:/Web/Database/openlistdata:/opt/openlist/data"
      - "C:/Web/Database/openlistimg:/web/img"
      - "E:/Web/list:/web/list"
    restart: unless-stopped
    environment:
      - UMASK=022
