name: webwin

services:
  nginx:
    image: nginx:latest
    container_name: winnginx
    network_mode: "host"
    # ports:
    #  - "80:80"
    volumes:
      - "C:/Web/web/conf/config/nginxwin:/etc/nginx/conf.d"
      - "E:/Web/vid:/web/vid"
    restart: unless-stopped
