# Define the variable
map $host $i_base_url {
    default http://i.mazey.net;
}

map $host $blog_base_url {
    default http://blog.mazey.net;
}

server {
    listen 80;
    server_name mazey.net www.mazey.net kb.mazey.net dev.mazey.net;
    root /web/mazey/www;
    index index.html;

    location = / {
        return 301 http://mazey.cn/index.html;
    }

    # /baby/
    rewrite ^/baby/blog/archives/(\d+)$ $blog_base_url/$1.html permanent;
    rewrite ^/baby/blog/?$ $blog_base_url/ permanent;
    rewrite ^/baby/blog/archives/([a-zA-Z]+/.*)$ $blog_base_url/$1.html permanent;
    rewrite ^/baby/blog/page/(\d+)$ $blog_base_url/page/$1.html permanent;
    rewrite ^/baby/(.*)$ $blog_base_url/ permanent;

    # /app/
    rewrite ^/app/((?:remind|sakura|share|speech)/.*)$ $i_base_url/x/$1 permanent;
    rewrite ^/app/((?:shuxin|visitor|xueyuting)/.*)$ $i_base_url/x/p/$1 permanent;
    rewrite ^/app/douban-bootstrap/(.*)$ $i_base_url/bootstrap-blueprints/$1 permanent;

    # kb.mazey.net
    # http://kb.mazey.net/
    if ($host = kb.mazey.net) {
        rewrite ^(.*)$ $i_base_url/x/kb$1 permanent;
    }

    include /web/conf/includes/security.conf;
    include /web/conf/includes/static.conf;
}
